site_name: COMP423 Course Notes
theme:
  name: material
features:
  - navigation.sections
  - navigation.tracking
  - navigation.instant
  - navigation.instant.progress
  - navigation.expand
  - navigation.tabs
  - navigation.indexes